<?php
/**
 * diary/tts.php — neural read-aloud audio for a Diary article.
 *
 *   /diary/tts.php?slug=<article>&t=<sentence text>
 *
 * Returns audio (mp3) for one sentence of the article, generated by the
 * configured engine (lib/Tts.php) and cached on disk by content hash so each
 * sentence is synthesised once. The <audio> player in diary.js points its src
 * here. Falls back (503) to the browser reader when no engine is configured.
 *
 * Anti-abuse: only synthesises text that actually belongs to the published
 * article (so it can't be used as an open TTS proxy), length-capped and
 * rate-limited per IP.
 */
declare(strict_types=1);
require_once dirname(__DIR__) . '/lib/bootstrap.php';

header('X-Content-Type-Options: nosniff');

function tts_fail(int $code, string $msg): void
{
    http_response_code($code);
    header('Content-Type: application/json; charset=utf-8');
    echo json_encode(['ok' => false, 'error' => $msg]);
    exit;
}

if (!Tts::available()) tts_fail(503, 'Read-aloud is not configured.');

$slug = preg_replace('/[^a-z0-9\-]/', '', strtolower((string) ($_GET['slug'] ?? '')));
$text = trim((string) ($_GET['t'] ?? ($_GET['text'] ?? '')));
if ($slug === '' || $text === '') tts_fail(400, 'Missing slug or text.');
if (mb_strlen($text) > 800) tts_fail(413, 'Passage too long.');

// Rate-limit: enough for a long article's first listen, then everything is cached.
if (!av_rate_ok('tts', 400, 600)) tts_fail(429, 'Too many requests — try again shortly.');

$article = (new DiaryRepository())->bySlug($slug);   // published only
if (!$article) tts_fail(404, 'Article not found.');

// The requested passage must be part of the article body (anti-abuse). Compare
// case-insensitively with collapsed whitespace and entities decoded, so it
// matches what the browser's textContent sends.
$norm = function (string $s): string {
    return trim(preg_replace('/\s+/u', ' ', mb_strtolower(html_entity_decode(strip_tags($s), ENT_QUOTES | ENT_HTML5, 'UTF-8'))));
};
$haystack = $norm(($article['title'] ?? '') . ' ' . ($article['dek'] ?? '') . ' ' . ($article['body_html'] ?? ''));
$needle = $norm($text);
if ($needle === '' || mb_strpos($haystack, $needle) === false) tts_fail(403, 'Passage is not part of this article.');

// Content-addressed cache — synthesise each unique passage/voice once.
$ext = Tts::ext();
$key = hash('sha256', Tts::engine() . '|' . Tts::voice() . '|' . $needle);
$dir = AV_ROOT . '/data/tts';
if (!is_dir($dir)) @mkdir($dir, 0775, true);
$path = $dir . '/' . $key . '.' . $ext;

$bytes = is_file($path) ? (string) file_get_contents($path) : null;
if ($bytes === null || $bytes === '') {
    $bytes = Tts::synthesize($text);
    if ($bytes === null || $bytes === '') tts_fail(502, 'Could not generate audio.');
    // Atomic write so a concurrent request never serves a half-written file.
    $tmp = $path . '.' . bin2hex(random_bytes(4)) . '.tmp';
    if (@file_put_contents($tmp, $bytes) !== false) @rename($tmp, $path);
}

header('Content-Type: ' . Tts::mimeType());
header('Content-Length: ' . strlen($bytes));
header('Cache-Control: public, max-age=31536000, immutable');   // safe: hash-named
echo $bytes;
