<?php
/**
 * lib/Sitemap.php — auto-maintained sitemap.xml + robots.txt.
 *
 * Writes physical files at the document root so they are authoritative
 * (WordPress can never override a real file). Rebuilt automatically when
 * content changes (admin saves) and lazily refreshed on the public index
 * pages. Best-effort: if the docroot isn't writable, the committed files
 * remain in place and nothing breaks.
 */
declare(strict_types=1);

final class Sitemap
{
    private const STATIC_PAGES = [
        ['', '1.0', 'weekly'],
        ['about/', '0.8', 'monthly'],
        ['ethos/', '0.9', 'monthly'],
        ['academy/', '0.9', 'weekly'],
        ['diary/', '0.9', 'weekly'],
        ['projects', '0.7', 'monthly'],
        ['events/', '0.7', 'weekly'],
        ['contact/', '0.5', 'yearly'],
        ['donate.html', '0.8', 'monthly'],
    ];

    /** Rebuild sitemap.xml + robots.txt. Returns true if the sitemap was written. */
    public static function rebuild(): bool
    {
        $ok = @file_put_contents(AV_ROOT . '/sitemap.xml', self::buildXml(), LOCK_EX) !== false;
        @file_put_contents(AV_ROOT . '/robots.txt', self::buildRobots(), LOCK_EX);
        return $ok;
    }

    /** Rebuild only if the sitemap is missing or older than $maxAge seconds. */
    public static function ensureFresh(int $maxAge = 3600): void
    {
        $f = AV_ROOT . '/sitemap.xml';
        if (!is_file($f) || (time() - (int) @filemtime($f)) > $maxAge) {
            self::rebuild();
        }
    }

    private static function buildXml(): string
    {
        $S = rtrim(SITE_URL, '/');
        $esc = fn($s) => htmlspecialchars((string) $s, ENT_QUOTES, 'UTF-8');
        $rows = [];
        foreach (self::STATIC_PAGES as [$path, $pri, $freq]) {
            $img = $path === 'ethos/' ? "$S/assets/img/ethos-og.webp" : '';
            $rows[] = ['loc' => "$S/$path", 'pri' => $pri, 'freq' => $freq, 'img' => $img];
        }
        try {
            foreach ((new DiaryRepository())->all() as $a) {
                $rows[] = ['loc' => "$S/diary/{$a['slug']}/", 'pri' => $a['featured'] ? '0.8' : '0.7',
                    'freq' => 'monthly', 'lastmod' => $a['published_at'], 'img' => "$S/diary/og/{$a['slug']}.png", 'title' => $a['title']];
            }
        } catch (Throwable $e) {}
        try {
            foreach ((new AcademyRepository())->all() as $c) {
                $rows[] = ['loc' => "$S/academy/{$c['slug']}/", 'pri' => $c['featured'] ? '0.8' : '0.7', 'freq' => 'monthly',
                    'img' => "$S/academy/og/{$c['slug']}.png", 'title' => $c['title']];
            }
        } catch (Throwable $e) {}

        $out = '<?xml version="1.0" encoding="UTF-8"?>' . "\n"
             . '<!-- Auto-generated by the custom app · authoritative real file (WordPress cannot override). -->' . "\n"
             . '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">' . "\n";
        foreach ($rows as $r) {
            $out .= "  <url>\n    <loc>" . $esc($r['loc']) . "</loc>\n";
            if (!empty($r['lastmod'])) $out .= "    <lastmod>" . $esc($r['lastmod']) . "</lastmod>\n";
            $out .= "    <changefreq>{$r['freq']}</changefreq>\n    <priority>{$r['pri']}</priority>\n";
            if (!empty($r['img'])) {
                $out .= "    <image:image><image:loc>" . $esc($r['img']) . "</image:loc>";
                if (!empty($r['title'])) $out .= "<image:title>" . $esc($r['title']) . "</image:title>";
                $out .= "</image:image>\n";
            }
            $out .= "  </url>\n";
        }
        return $out . "</urlset>\n";
    }

    private static function buildRobots(): string
    {
        $S = rtrim(SITE_URL, '/');
        return "# Afrovanguard — robots.txt (auto-maintained by the custom app; authoritative real file)\n"
            . "User-agent: *\nAllow: /\n\n"
            . "# Server internals (also blocked at directory level)\n"
            . "Disallow: /lib/\nDisallow: /db/\nDisallow: /admin/\nDisallow: /error.php\n\n"
            . "# Sitemaps — custom first (authoritative), then WordPress core's own.\n"
            . "Sitemap: $S/sitemap.xml\nSitemap: $S/diary/sitemap.xml\nSitemap: $S/academy/sitemap.xml\nSitemap: $S/wp-sitemap.xml\n";
    }
}
